---
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    users:
    - riku
    - tuomo
  tasks:
  - name: install python 2
    raw: apt -y update && apt install -y python-minimal python-zipstream

  - name: Create users from public keys
    user:
      name: "{{ item }}"
      shell: /bin/bash
      group: sudo
    with_items: "{{ users }}"

  - name: Enable passwordless sudo
    lineinfile:
      dest: "/etc/sudoers.d/{{ item }}"
      state: present
      create: yes
      regexp: "{{ item }} .*"
      line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    with_items: "{{ users }}"

  - name: Add public keys
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'pubkeys/'+item) }}"
      state: present
    with_items: "{{ users }}"

  - name: Create locales
    locale_gen:
      name: fi_FI.UTF-8
      state: present
