---

- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

- name: Add mongodb repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"
    state: present

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present

- name: Enable mongodb
  service:
    name: mongod
    enabled: yes
    state: started
