---
- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - htop
  - python-pip
  - protobuf-compiler
  - python-dev
  - python-tk

- name: Install pip packages
  pip:
    name: "{{ item }}"
  with_items:
  - virtualenv

- name: Clone sikatrain repo
  git:
    repo: 'https://github.com/tuomoko/sikatrain.git'
    dest: /home/{{ tensorflow_user }}/sikatrain
    version: master
  become_user: "{{ tensorflow_user }}"

- name: Clone tensorflow models repo
  git:
    repo: 'https://github.com/tensorflow/models.git'
    dest: /home/{{ tensorflow_user }}/models
    version: master
  become_user: "{{ tensorflow_user }}"

- name: Install tensorflow deps for production environment
  pip:
    virtualenv: /home/{{ tensorflow_user }}/production-env
    extra_args: "--no-cache-dir"
    requirements: /home/{{ tensorflow_user }}/sikatrain/api/requirements.txt
  become_user: "{{ tensorflow_user }}"

- name: Compile protobuf
  shell: protoc object_detection/protos/*.proto --python_out=.
  args:
    chdir: /home/{{ tensorflow_user }}/models/research
  become_user: "{{ tensorflow_user }}"

- name: Install systemd service
  template:
    src: sika_api.service.j2
    dest: /etc/systemd/system/sika_api.service
  notify:
  - reload systemd
  - restart sika_api

- name: Enable sika_api service
  service:
    name: sika_api
    state: started
    enabled: yes
