---
- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - htop
  - python-pip
  - protobuf-compiler

- name: Install pip packages
  pip:
    name: "{{ item }}"
  with_items:
  - virtualenv

- name: Install tensorflow deps for production environment
  pip:
    name: "{{ item }}"
    virtualenv: /opt/production-env
    extra_args: "--no-cache-dir"
  with_items:
  - tensorflow
