---
- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - htop
  - python-pip
  - protobuf-compiler

- name: Install pip packages
  pip:
    name: "{{ item }}"
  with_items:
  - virtualenv

- name: Clone sikatrain repo
  git:
    repo: 'https://github.com/tuomoko/sikatrain.git'
    dest: /opt/sikatrain
    version: master

- name: Clone tensorflow models repo
  git:
    repo: 'https://github.com/tensorflow/models.git'
    dest: /opt/models
    version: master

- name: Install tensorflow deps for production environment
  pip:
    virtualenv: /opt/production-env
    extra_args: "--no-cache-dir"
    requirements: /opt/sikatrain/api/requirements.txt
